title: "Saurav R - Software Engineer, 3D Simulation Expert & Machine Learning Engineer"  # Replace with your full name
description: "learning keeps me up at night."
favicon: path/to/your/favicon.ico
gems:
  [
    jekyll-theme-cayman  # Replace with your desired theme (consider options below)
  ]
theme: jekyll-theme-cayman  # Replace with your desired theme
primary_color: "#FFFFFF"  # Dark Gray (text and accents)
secondary_color: "#800080"  # Light Gray (background)
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor", "_config.yml"]
