# Jekyll configuration file

title: "Saurav R - Software Engineer, Simulation expert and Machine learning enthusiast"  # Replace with your name
description: Curiosity keeps me awake at night.
# You can add custom favicon details here (16x16 pixels)
# favicon: path/to/your/favicon.ico

# Jekyll Gems (add any additional gems you might use)
gems:
    - jekyll-theme-cayman  # Replace with your desired theme


# Theme Configuration (adjust based on the chosen theme)
theme: jekyll-theme-cayman  # Replace with your desired theme
# You can customize the theme options here based on its documentation

# Collections (optional, for managing blog posts or similar content)
# collections:

# Pagination (optional, for paginating content)
# permalink: /:categories/:year/:month/:day/:title.html
# paginate: 5

# Other Jekyll configuration options (refer to Jekyll documentation for details)
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  # ... other kramdown options

# You can add custom variables here to use within your Jekyll templates

exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor", "_config.yml"]
</blockquote>
